export default [
  {
    key: "1",
    name: "Model S",
    tagline: "Starting at $69,420",
    content: "Existing Inventory",
    image: require("../../assets/images/ModelS.jpeg"),
    PrimaryUrl: "https://www.tesla.com/models/design#overview",
    secondaryUrl: "https://www.tesla.com/inventory/new/ms",
  },
  {
    key: "2",
    name: "Model 3",
    tagline: "Order Online for ",
    taglineCTA: "Touchless Delivery",
    content: "Existing Inventory",
    image: require("../../assets/images/Model3.jpeg"),
    PrimaryUrl: "https://www.tesla.com/model3/design#overview",
    secondaryUrl: "https://www.tesla.com/inventory/new/m3",
  },
  {
    key: "3",
    name: "Model X",
    tagline: "Order Online for ",
    taglineCTA: "Touchless Delivery",
    content: "Learn More",
    image: require("../../assets/images/ModelX.jpeg"),
    PrimaryUrl: "https://www.tesla.com/modelx/design#overview",
    secondaryUrl: "https://www.tesla.com/inventory/new/mx",
  },
  {
    key: "4",
    name: "Model Y",
    tagline: "Order Online for ",
    taglineCTA: "Touchless Delivery",
    content: "Existing Inventory",
    image: require("../../assets/images/ModelY.jpeg"),
    primaryUrl: "https://www.tesla.com/modely/design#overview",
    secondaryUrl: "https://www.tesla.com/modely",
  },
];
